export const MSG_CONST = {
    ADD_OK: 'Adicionado com sucesso!',
    ADD_ERROR: 'Erro ao adicionar as informações!',
    AGREE_TEXT: 'Sim, prosseguir',
    ADD_FILE_OK: 'Arquivo adicionado com sucesso!',
    ADD_FILE_ERROR: 'Erro ao adicionar o arquivo! Tente novamente.',
    BACK_TO_START: 'Voltar ao início',
    CHANGE_ROLE_OK: 'Função alterada com sucesso!',
    CHANGE_ROLE_ERROR: 'Erro ao alterar a função do usuário.',
    COULD_NOT_REGISTER: 'Não foi possivel cadastrar, confira seus dados e tente novamente.',
    COULD_NOT_CONTRACT: 'Não foi possível finalizar a contratação.',
    CONFIRM_TITLE: 'Você tem certeza?',
    CONFESSION_PAYMENT_TITLE: 'Já recebemos a escolha do seu pagamento',
    CONFESSION_DESCRIPTION: 'Agora, basta aguardar a confirmação! Fique tranquilo que você será informado do progresso.',
    DATA_FAIL: 'Não conseguimos carregar seus dados, tente mais tarde.',
    DELETE_FILE_OK: 'Arquivo deletado com sucesso!',
    INVALID_FIELD: 'Informações inválidas, revise e tente novamente.',
    INSTALLMENT_NOT_PAIDED: 'A parcela ainda não foi paga.',
    DELETE_ACCOUNT_TEXT: 'Após clicar em prosseguir, vamos excluir a sua conta de nossa base de dados. É de extrema importância que tome essa decisão de forma consciente. Não prefere conversar com alguém antes?',
    DELETED_ACCOUNT_TITLE: 'Conta excluída com sucesso!',
    DELETE_ACCOUNT_ERROR: 'Erro ao excluir a conta',
    DELETE_ITEM_TITLE: 'Deseja excluir este item?',
    DELETE_ITEM_TEXT: 'Caso você decida prosseguir, o(s) dado(s) escolhido(s) será excluído(s) permanentemente.',
    DELETE_PROFILE_TITLE: 'Deseja excluir ',
    DELETE_PROFILE_TEXT: 'Caso você decida prosseguir, o perfil será excluído permanentemente.',
    DELETED_DATA_OK: 'Excluído com sucesso!',
    DELETED_DATA_ERROR: 'Erro ao excluir os dados!',
    DELETED_INGREDIENT_ERROR: 'Erro ao excluir o ingrediente.',
    DELETED_INGREDIENT_OK: 'Ingrediente excluído com sucesso!',
    DELETED_RECIPE_ERROR: 'Erro ao excluir a receita.',
    DELETED_RECIPE_OK: 'Receita excluída com sucesso!',
    DISAGREE_TEXT: 'Mudei de ideia',
    EDIT_INGREDIENT_ERROR: 'Erro ao editar o ingrediente.',
    EDIT_INGREDIENT_OK: 'Ingrediente alterado com sucesso!',
    EDIT_IMAGE_OK: 'Imagem alterada com sucesso!',
    EDIT_IMAGE_ERROR: 'Erro ao alterar a imagem.',
    EDIT_MEASURES_TITLE: 'Deseja realmente alterar suas medidas corporais?',
    EDIT_MEASURES_OK: 'Suas medidas corporais foram alteradas com sucesso.',
    EDIT_MEASURES_ERROR: 'Erro ao alterar as medidas corporais.',
    EDIT_NAME_OK: 'Seu nome foi alterado com sucesso.',
    EDIT_NAME_ERROR: 'Erro ao alterar o nome.',
    EDIT_PASSWORD_OK: 'Senha alterada com sucesso.',
    EDIT_PASSWORD_ERROR: 'Erro ao editar a senha. Confira os dados.',
    EMAIL_ALREADY_IN_USE: 'Email já cadastrado, tente recuperar a senha ou outro email.',
    ERROR_TITLE: 'Erro!',
    ERROR_HAS_OCCURRED: 'Ocorreu um erro, tente novamente mais tarde.',
    EMAIL_ALREADY_IN_USE_CREATE: 'Email já cadastrado, tente outro email',
    EMPTY_FIELDS: 'Preencha email e senha corretamente',
    EMAIL_INVALID: 'Email inválido, tente novamente ou faça um cadastro!',
    IMPORT_DATA_ERROR: 'Erro ao importar os dados.',
    IMPORT_DATA_OK: ' alimentos importados com sucesso!',
    LOGIN_ERROR: 'Erro ao tentar acessar sua conta.',
    NOT_AVAILABLE: 'Função indisponível nessa versão.',
    NOT_AVAILABLE_DESKTOP: 'Função indisponível na versão para desktop, apenas no app.',
    NOTIFICATION_DELETE_SUCCESSFUL: 'Erro ao excluir a notificação.',
    NOTIFICATION_DELETE_ERROR: 'Erro ao excluir a notificação.',
    PLAN_CHANGE_OK: 'Plano alterado com sucesso!',
    REGISTER_OK: 'Cadastro finalizado com sucesso!',
    REGISTER_ERROR: 'Ocorreu um erro no cadastro, tente novamente mais tarde.',
    RENEGOTIATE_TEXT: 'Ao clicar em prosseguir, você está negando a proposta atual para tentar uma nova. Não podemos garantir que você consiga as mesmas condições apresentadas nesse acordo novamente. Não prefere conversar com alguém antes?',
    REQUIRED_FIELDS: 'Os campos são obrigatórios',
    RESET_SUCCESSFUL: 'Reset enviado com sucesso!',
    RESET_DESCRIPTION: 'Enviamos as instruções para você recuperar a sua senha! Confira sua caixa de email e após, tente o login novamente.',
    REQUEST_SENT: 'Solicitação enviada',
    RESET_PASSWORD_DESCRIPTION: 'Uma solicitação foi enviada para seu email com os passos para a recuperação de senha.',
    SAVE_DATA_ERROR: 'Erro ao salvar os dados.',
    SAVE_DATA_OK: 'Dados salvos!',
    SERVIDOR_ERROR: 'Erro de comunicação com o servidor',
    TOO_MANY_REQUESTS: 'Excedeu o limite de solicitações para recuperar a senha. Tente mais tarde',
    TRY_AGAIN: 'Tente novamente',
    UNDERSTOOD_TEXT: 'Entendido',
    USER_DATA_ERROR: 'Erro ao retornar os dados do usuário.',
    USER_REGISTER_OK: 'Usuário cadastrado com sucesso!',
    USER_FOUND: 'Usuário encontrado',
    USER_DISABLED: 'Usuário desabilitado. Para maiores informações entre em contato com o nosso suporte.',
    USER_NOT_DOUND: 'Email não cadastrado, faça seu cadastro agora!',
    VIEW_DATA_ERROR: 'Erro ao retornar os dados.',
    WRONG_PASSWORD: 'Email ou senha estão incorretos, tente novamente.',
}