export const RECIPES = [
    { "id": "rapbK", "title": "Crepioca de queijo minas com peito de peru e cottage", "totalPortion": 130, "description": "Misture o ovo com a tapioca até formar uma massa homogênea, Aqueça uma frigideira antiaderente e despeje a mistura, espalhando uniformemente, Cozinhe em fogo médio até a massa firmar, Adicione o queijo minas, o peito de peru e o queijo cottage sobre a crepioca, Dobre a crepioca ao meio, aquecendo até o queijo derreter.", "favorited": null, "ingredientsIds": ["7V3Ll", "KwqlVhnui0ARRUYPKF3P", "zDJLW", "PsCRjdAvTazopqqFWBjp", "JWyPO9JyBj1MESGr58JC"], "ingredients": [{ "favorited": null, "showIn": ["recipes", "menu"], "totalFat": 0, "image": null, "type": "carbo", "portionIncrement": 5, "transFats": 0, "groups": ["cassava"], "id": "7V3Ll", "addedSugars": 0, "proteins": 0, "dietaryFiber": 0, "energeticValue": 44.8, "portionMax": 999, "totalSugars": 0, "title": "Tapioca", "totalCarbohydrates": 11.2, "sodium": 0, "restrictions": [], "saturatedFat": 0, "totalPortion": 20, "position": 1 }, { "saturatedFat": 0, "addedSugars": 0, "totalFat": 4.4, "transFats": 0, "dietaryFiber": 0, "id": "KwqlVhnui0ARRUYPKF3P", "totalCarbohydrates": 0.55, "title": "Ovo de galinha inteiro cru ", "totalPortion": 55, "energeticValue": 78.65, "type": "protein", "proteins": 7.15, "showIn": ["recipes"], "portionIncrement": 0, "portionMax": 55, "favorited": null, "restrictions": ["lactovegetarian", "vegan"], "groups": ["eggs-and-derivatives"], "image": null, "sodium": 91.85, "position": 2, "totalSugars": 0 }, { "totalCarbohydrates": 0.6, "groups": ["dairy-products"], "title": "Queijo minas frescal", "position": 3, "transFats": 0, "totalPortion": 20, "energeticValue": 52.8, "portionIncrement": 20, "id": "zDJLW", "portionMax": 60, "addedSugars": 0, "image": null, "saturatedFat": 0, "totalSugars": 0, "favorited": null, "type": "protein", "dietaryFiber": 0, "totalFat": 4, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "showIn": ["recipes"], "proteins": 3.4, "sodium": 6.2 }, { "sodium": 200, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian", "irritable"], "totalFat": 0.4, "totalCarbohydrates": 0.48, "title": "Peito de peru defumado", "image": null, "favorited": null, "position": 4, "portionMax": 60, "groups": ["turkey"], "dietaryFiber": 0, "energeticValue": 21.4, "saturatedFat": 0.12, "id": "PsCRjdAvTazopqqFWBjp", "addedSugars": 0, "type": "protein", "totalSugars": 0, "portionIncrement": 20, "showIn": ["recipes", "menu"], "transFats": 0, "proteins": 4, "totalPortion": 20 }, { "transFats": 0, "groups": ["dairy-products"], "totalSugars": 0, "image": null, "saturatedFat": 0.165, "title": "Queijo cottage", "addedSugars": 0, "portionIncrement": 5, "type": "protein", "totalPortion": 15, "favorited": null, "portionMax": 40, "restrictions": ["allergic", "intolerant", "vegan", "ovovegetarian", "irritable"], "energeticValue": 13.5, "sodium": 54.3, "totalCarbohydrates": 0.39, "totalFat": 0.54, "position": 5, "proteins": 1.74, "showIn": ["recipes"], "id": "JWyPO9JyBj1MESGr58JC", "dietaryFiber": 0 }], "image": null, "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "restrictions": ["lactovegetarian", "vegan", "irritable", "intolerant", "ovovegetarian", "allergic", "ovolactovegetarian"] },
    { "id": "eOsyV", "title": "Crepioca de queijo minas com presunto e cottage", "totalPortion": 130, "description": "Misture o ovo com a tapioca até formar uma massa homogênea, Aqueça uma frigideira antiaderente e despeje a mistura, espalhando uniformemente, Cozinhe em fogo médio até a massa firmar, Adicione o queijo minas, o presunto e o queijo cottage sobre a crepioca, Dobre a crepioca ao meio, aquecendo até o queijo derreter.", "ingredients": [{ "showIn": ["recipes", "menu"], "sodium": 0, "totalSugars": 0, "image": null, "dietaryFiber": 0, "energeticValue": 44.8, "position": 1, "restrictions": [], "portionIncrement": 5, "id": "7V3Ll", "proteins": 0, "type": "carbo", "saturatedFat": 0, "addedSugars": 0, "totalFat": 0, "title": "Tapioca", "transFats": 0, "groups": ["cassava"], "totalPortion": 20, "favorited": null, "portionMax": 999, "totalCarbohydrates": 11.2 }, { "type": "protein", "favorited": null, "energeticValue": 78.65, "totalCarbohydrates": 0.55, "totalFat": 4.4, "showIn": ["recipes"], "portionIncrement": 0, "proteins": 7.15, "totalPortion": 55, "id": "KwqlVhnui0ARRUYPKF3P", "addedSugars": 0, "saturatedFat": 0, "restrictions": ["lactovegetarian", "vegan"], "dietaryFiber": 0, "groups": ["eggs-and-derivatives"], "title": "Ovo de galinha inteiro cru ", "position": 2, "transFats": 0, "totalSugars": 0, "image": null, "portionMax": 55, "sodium": 91.85 }, { "addedSugars": 0, "sodium": 6.2, "id": "zDJLW", "favorited": null, "showIn": ["recipes"], "groups": ["dairy-products"], "title": "Queijo minas frescal", "dietaryFiber": 0, "portionMax": 60, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "totalFat": 4, "type": "protein", "position": 3, "portionIncrement": 20, "energeticValue": 52.8, "transFats": 0, "saturatedFat": 0, "totalCarbohydrates": 0.6, "image": null, "totalSugars": 0, "proteins": 3.4, "totalPortion": 20 }, { "totalFat": 0.4, "showIn": ["recipes", "menu"], "title": "Presunto magro", "totalCarbohydrates": 0.4, "id": "qQNih", "dietaryFiber": 0, "portionIncrement": 20, "addedSugars": 0, "sodium": 207.8, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalPortion": 20, "groups": ["pork"], "type": "protein", "saturatedFat": 0, "transFats": 0, "proteins": 2.8, "totalSugars": 0, "energeticValue": 18.6, "portionMax": 60, "position": 4 }, { "totalPortion": 15, "groups": ["dairy-products"], "totalSugars": 0, "energeticValue": 13.5, "portionIncrement": 5, "showIn": ["recipes"], "saturatedFat": 0.165, "totalFat": 0.54, "title": "Queijo cottage", "image": null, "position": 5, "type": "protein", "id": "JWyPO9JyBj1MESGr58JC", "proteins": 1.74, "dietaryFiber": 0, "restrictions": ["allergic", "intolerant", "vegan", "ovovegetarian", "irritable"], "addedSugars": 0, "portionMax": 40, "transFats": 0, "totalCarbohydrates": 0.39, "favorited": null, "sodium": 54.3 }], "ingredientsIds": ["7V3Ll", "KwqlVhnui0ARRUYPKF3P", "zDJLW", "qQNih", "JWyPO9JyBj1MESGr58JC"], "restrictions": ["lactovegetarian", "vegan", "irritable", "intolerant", "ovovegetarian", "allergic", "ovolactovegetarian"], "favorited": null, "image": null, "usedIn": ["breakfast", "morning-snack", "snack", "supper"] },
    { "id": "SV09U", "title": "Cuscuz de atum com margarina", "totalPortion": 55, "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian", "irritable"], "favorited": null, "ingredients": [{ "dietaryFiber": 1.68, "title": "Cuscuz de milho cru", "favorited": null, "image": null, "position": 1, "totalSugars": 0, "showIn": ["recipes"], "type": "carbo", "totalFat": 0.48, "energeticValue": 107.4, "totalCarbohydrates": 24, "portionIncrement": 1, "proteins": 2.16, "transFats": 0, "totalPortion": 30, "saturatedFat": 0, "id": "o90kdiNEGQglTamFzVsN", "restrictions": [], "sodium": 13.8, "addedSugars": 0, "portionMax": 999, "groups": ["corn"] }, { "energeticValue": 26.892000000000003, "totalSugars": 0, "position": 2, "title": "Atum sólido natural", "totalCarbohydrates": 0, "addedSugars": 0, "favorited": null, "id": "s6FawgBn6QvqI7YCVpMo", "portionMax": 999, "proteins": 5.644, "transFats": 0, "saturatedFat": 0.16599999999999998, "type": "protein", "totalFat": 0.53, "portionIncrement": 5, "showIn": ["menu", "lunch", "dinner", "recipes"], "totalPortion": 20, "image": null, "groups": ["fish-seafood"], "dietaryFiber": 0, "sodium": 82.336, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"] }, { "title": "Margarina sem sal (80% de lipídeos)", "totalFat": 4.05, "type": "fat", "groups": ["margarine"], "portionIncrement": 1, "portionMax": 20, "addedSugars": 0, "id": "DvlwI", "totalPortion": 5, "sodium": 3.85, "totalSugars": 0, "showIn": ["recipes"], "saturatedFat": 0, "proteins": 0, "position": 3, "energeticValue": 36.1, "dietaryFiber": 0, "transFats": 0, "restrictions": ["irritable"], "totalCarbohydrates": 0 }], "image": null, "description": "Hidrate o cuscuz com água e deixe descansar por 5 minutos, Cozinhe o cuscuz no vapor por cerca de 10 minutos até ficar macio, Misture o cuscuz cozido com o atum, Adicione a margarina e misture bem, Sirva quente ou frio, conforme preferir", "ingredientsIds": ["o90kdiNEGQglTamFzVsN", "s6FawgBn6QvqI7YCVpMo", "DvlwI"] },
    { "id": "kWBhp", "title": "Misto quente (pão de forma) Queijo minas com peito de frango e requeijão light (SEM LACTOSE)", "totalPortion": 105, "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "description": "Monte o sanduíche com uma fatia de pão de forma, queijo minas, peito de frango e requeijão, Cubra com outra fatia de pão de forma, Aqueça uma sanduicheira ou frigideira e toste o sanduíche até dourar, Sirva quente.", "restrictions": ["celiac", "irritable", "allergic", "vegan", "ovovegetarian", "ovolactovegetarian", "lactovegetarian"], "ingredients": [{ "type": "carbo", "title": "Pão de forma", "totalPortion": 50, "sodium": 253, "portionMax": 100, "proteins": 4.5, "energeticValue": 126.5, "favorited": null, "groups": ["bread"], "transFats": 0, "showIn": ["recipes"], "totalCarbohydrates": 24.5, "saturatedFat": 0, "totalFat": 1.5, "id": "vuRQG", "dietaryFiber": 3, "image": null, "position": 1, "restrictions": ["celiac", "irritable"], "totalSugars": 0, "addedSugars": 0, "portionIncrement": 25 }, { "energeticValue": 50.2, "totalSugars": 0, "sodium": 50.6, "groups": ["dairy-products"], "saturatedFat": 2.4, "proteins": 3.8, "showIn": ["recipes"], "favorited": null, "totalPortion": 20, "dietaryFiber": 0, "id": "N5x8bJTHxGphJ74N9AHN", "title": "Queijo minas frescal (sem lactose)", "type": "protein", "totalCarbohydrates": 0.2, "transFats": 0.14, "restrictions": ["allergic", "vegan", "ovovegetarian", "irritable"], "totalFat": 3.8, "image": null, "portionIncrement": 20, "position": 2, "addedSugars": 0, "portionMax": 80 }, { "title": "Peito de frango defumado", "portionIncrement": 20, "totalSugars": 0, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian", "irritable"], "portionMax": 80, "energeticValue": 16.4, "id": "QexKz8nBO2mlhj9vSK0Q", "sodium": 231, "totalPortion": 20, "position": 3, "proteins": 3.7, "favorited": null, "image": null, "transFats": 0, "addedSugars": 0, "saturatedFat": 0.1, "type": "protein", "dietaryFiber": 0, "showIn": ["recipes", "menu"], "groups": ["chicken"], "totalFat": 0.2, "totalCarbohydrates": 0.5 }, { "sodium": 87.912, "type": "protein", "position": 4, "totalCarbohydrates": 0, "portionMax": 60, "totalSugars": 0, "portionIncrement": 5, "saturatedFat": 1.2987, "id": "XakUSvj0MSkopgKk8c8w", "title": "Requeijão light (zero lactose)", "favorited": null, "addedSugars": 0, "proteins": 1.94805, "image": null, "energeticValue": 26.22375, "restrictions": ["allergic", "vegan", "ovovegetarian", "irritable"], "showIn": ["recipes"], "dietaryFiber": 0, "totalPortion": 15, "transFats": 0, "groups": ["dairy-products"], "totalFat": 2.0479499999999997 }], "ingredientsIds": ["vuRQG", "N5x8bJTHxGphJ74N9AHN", "QexKz8nBO2mlhj9vSK0Q", "XakUSvj0MSkopgKk8c8w"] },
    { "id": "VwdZY", "title": "Misto quente (pão de forma) de atum com creme de ricota", "totalPortion": 105, "description": "Misture o atum com o creme de ricota e um fio de azeite, Monte o sanduíche com uma fatia de pão de forma e a mistura de atum, Cubra com outra fatia de pão de forma, Aqueça uma sanduicheira ou frigideira e toste o sanduíche até dourar.", "ingredientsIds": ["s6FawgBn6QvqI7YCVpMo", "KioagnFdv0Dv8HAQSZ39", "6FwJLwfWdTt1kPwMoeBU", "vuRQG"], "ingredients": [{ "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"], "portionIncrement": 5, "title": "Atum sólido natural", "saturatedFat": 0.16599999999999998, "dietaryFiber": 0, "totalFat": 0.53, "totalPortion": 20, "addedSugars": 0, "totalCarbohydrates": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "favorited": null, "id": "s6FawgBn6QvqI7YCVpMo", "position": 2, "portionMax": 999, "energeticValue": 26.892000000000003, "sodium": 82.336, "type": "protein", "transFats": 0, "image": null, "totalSugars": 0, "proteins": 5.644, "groups": ["fish-seafood"] }, { "totalPortion": 20, "energeticValue": 39.6, "restrictions": ["allergic", "intolerant", "vegan", "ovovegetarian", "irritable"], "totalSugars": 0, "totalCarbohydrates": 0.5940000000000001, "addedSugars": 0, "showIn": ["recipes"], "saturatedFat": 2.31, "title": "Creme de ricota", "id": "KioagnFdv0Dv8HAQSZ39", "portionIncrement": 5, "image": null, "groups": ["dairy-products"], "sodium": 69.2, "proteins": 1.7819999999999998, "dietaryFiber": 0, "totalFat": 3.3659999999999997, "portionMax": 80, "position": 3, "favorited": null, "type": "protein", "transFats": 0 }, { "type": "fat", "title": "Azeite de oliva extra virgem", "dietaryFiber": 0, "image": null, "transFats": 0, "portionMax": 25, "addedSugars": 0, "favorited": null, "portionIncrement": 1, "totalFat": 5, "energeticValue": 44.2, "totalSugars": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "saturatedFat": 0, "restrictions": [], "groups": ["vegetable-oils"], "sodium": 0, "totalPortion": 5, "totalCarbohydrates": 0, "proteins": 0, "id": "6FwJLwfWdTt1kPwMoeBU", "position": 4 }, { "saturatedFat": 0, "sodium": 253, "type": "carbo", "favorited": null, "energeticValue": 126.5, "totalPortion": 50, "id": "vuRQG", "portionMax": 100, "proteins": 4.5, "showIn": ["recipes"], "restrictions": ["celiac", "irritable"], "totalSugars": 0, "image": null, "dietaryFiber": 3, "totalCarbohydrates": 24.5, "transFats": 0, "position": 1, "addedSugars": 0, "groups": ["bread"], "title": "Pão de forma", "totalFat": 1.5, "portionIncrement": 25 }], "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian", "allergic", "intolerant", "irritable", "celiac"], "usedIn": ["breakfast", "morning-snack", "snack", "supper"] },
    { "id": "exeCb", "title": "Misto quente (pão francês) de carne moída com manteiga com sal", "totalPortion": 75, "description": "Corte o pão francês ao meio, espalhe manteiga com sal em uma metade, coloque a carne moída cozida, feche o sanduíche e aqueça.", "ingredients": [{ "groups": ["bread"], "totalSugars": 0, "position": 1, "portionIncrement": 50, "saturatedFat": 0, "dietaryFiber": 1, "id": "5QTtj", "addedSugars": 0, "proteins": 3.5, "showIn": ["recipes"], "transFats": 0, "sodium": 323.5, "totalPortion": 50, "totalFat": 1.5, "portionMax": 100, "type": "carbo", "favorited": null, "energeticValue": 149.5, "title": "Pão francês", "restrictions": ["celiac", "irritable", "lactovegetarian", "vegan"], "totalCarbohydrates": 29, "image": null }, { "position": 2, "showIn": ["menu", "lunch", "dinner", "recipes"], "energeticValue": 43.8, "portionIncrement": 5, "groups": ["beef"], "favorited": null, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"], "proteins": 7, "totalFat": 1.4, "image": null, "title": "Carne moída de primeira cozida", "id": "K4VV3", "portionMax": 999, "totalPortion": 20, "saturatedFat": 0, "addedSugars": 0, "type": "protein", "dietaryFiber": 0, "sodium": 0, "totalCarbohydrates": 0, "totalSugars": 0, "transFats": 0 }, { "transFats": 0, "totalCarbohydrates": 0, "addedSugars": 0, "position": 3, "dietaryFiber": 0, "energeticValue": 36.25, "saturatedFat": 0, "title": "Manteiga com sal", "proteins": 0, "totalSugars": 0, "groups": ["dairy-products"], "id": "mz3DqjqwjdXwF4Dtx5yF", "portionMax": 20, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "portionIncrement": 1, "showIn": ["recipes"], "sodium": 28.9, "type": "fat", "totalPortion": 5, "totalFat": 4.1 }], "restrictions": ["celiac", "irritable", "lactovegetarian", "vegan", "ovolactovegetarian", "ovovegetarian", "intolerant"], "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "ingredientsIds": ["5QTtj", "K4VV3", "mz3DqjqwjdXwF4Dtx5yF"] },
    { "id": "q36KS", "title": "Misto quente (pão francês) de queijo mussarela", "totalPortion": 70, "restrictions": ["celiac", "irritable", "lactovegetarian", "vegan", "intolerant", "ovovegetarian", "allergic"], "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "ingredientsIds": ["5QTtj", "9pnLo"], "description": "Corte o pão francês ao meio, coloque queijo mussarela sobre uma metade, feche o sanduíche e aqueça até o queijo derreter.", "ingredients": [{ "energeticValue": 149.5, "type": "carbo", "showIn": ["recipes"], "dietaryFiber": 1, "id": "5QTtj", "saturatedFat": 0, "title": "Pão francês", "portionIncrement": 50, "totalPortion": 50, "groups": ["bread"], "sodium": 323.5, "transFats": 0, "restrictions": ["celiac", "irritable", "lactovegetarian", "vegan"], "totalSugars": 0, "totalFat": 1.5, "totalCarbohydrates": 29, "image": null, "portionMax": 100, "proteins": 3.5, "position": 1, "favorited": null, "addedSugars": 0 }, { "energeticValue": 65.8, "type": "protein", "addedSugars": 0, "image": null, "dietaryFiber": 0, "portionIncrement": 20, "id": "9pnLo", "groups": ["dairy-products"], "favorited": null, "totalSugars": 0, "sodium": 116.2, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "saturatedFat": 0, "position": 2, "portionMax": 100, "totalCarbohydrates": 0.6, "totalFat": 5, "showIn": ["recipes"], "totalPortion": 20, "transFats": 0, "title": "Queijo mussarela", "proteins": 4.4 }] },
    { "id": "9PNax", "title": "Sanduíche (pão de forma) de queijo mussarela com peito de frango", "totalPortion": 90, "description": "Corte o pão de forma ao meio, coloque queijo mussarela e peito de frango defumado sobre uma metade, feche o sanduíche e aqueça até o queijo derreter.", "image": null, "favorited": null, "ingredients": [{ "energeticValue": 126.5, "dietaryFiber": 3, "id": "vuRQG", "sodium": 253, "addedSugars": 0, "totalSugars": 0, "type": "carbo", "portionMax": 100, "image": null, "totalFat": 1.5, "transFats": 0, "proteins": 4.5, "totalCarbohydrates": 24.5, "restrictions": ["celiac", "irritable"], "favorited": null, "totalPortion": 50, "position": 1, "title": "Pão de forma", "portionIncrement": 25, "groups": ["bread"], "saturatedFat": 0, "showIn": ["recipes"] }, { "sodium": 116.2, "position": 2, "totalPortion": 20, "portionMax": 80, "proteins": 4.4, "type": "protein", "id": "9pnLo", "transFats": 0, "dietaryFiber": 0, "groups": ["dairy-products"], "saturatedFat": 0, "totalCarbohydrates": 0.6, "favorited": null, "totalFat": 5, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "portionIncrement": 20, "showIn": ["recipes"], "totalSugars": 0, "addedSugars": 0, "title": "Queijo mussarela", "image": null, "energeticValue": 65.8 }, { "id": "QexKz8nBO2mlhj9vSK0Q", "totalPortion": 20, "portionMax": 80, "portionIncrement": 20, "totalCarbohydrates": 0.5, "sodium": 231, "position": 3, "title": "Peito de frango defumado", "totalFat": 0.2, "proteins": 3.7, "type": "protein", "image": null, "favorited": null, "addedSugars": 0, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian", "irritable"], "saturatedFat": 0.1, "energeticValue": 16.4, "showIn": ["recipes", "menu"], "totalSugars": 0, "groups": ["chicken"], "dietaryFiber": 0, "transFats": 0 }], "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "ingredientsIds": ["vuRQG", "9pnLo", "QexKz8nBO2mlhj9vSK0Q"], "restrictions": ["celiac", "irritable", "intolerant", "ovovegetarian", "vegan", "allergic", "ovolactovegetarian", "lactovegetarian"] },
    { "id": "OFVsP", "title": "Sanduíche (pão de forma) de queijo mussarela com presunto", "totalPortion": 90, "description": "Corte o pão de forma ao meio, Coloque queijo mussarela sobre uma metade, Adicione presunto magro sobre o queijo, Feche o sanduíche, Aqueça até o queijo derreter.", "ingredientsIds": ["vuRQG", "9pnLo", "qQNih"], "ingredients": [{ "title": "Pão de forma", "totalFat": 1.5, "favorited": null, "saturatedFat": 0, "portionMax": 100, "position": 1, "totalPortion": 50, "id": "vuRQG", "totalSugars": 0, "proteins": 4.5, "dietaryFiber": 3, "addedSugars": 0, "sodium": 253, "energeticValue": 126.5, "totalCarbohydrates": 24.5, "restrictions": ["celiac", "irritable"], "showIn": ["recipes"], "portionIncrement": 25, "type": "carbo", "image": null, "groups": ["bread"], "transFats": 0 }, { "transFats": 0, "position": 2, "totalPortion": 20, "id": "9pnLo", "showIn": ["recipes"], "energeticValue": 65.8, "totalCarbohydrates": 0.6, "proteins": 4.4, "type": "protein", "totalSugars": 0, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "favorited": null, "sodium": 116.2, "title": "Queijo mussarela", "portionIncrement": 20, "portionMax": 80, "addedSugars": 0, "totalFat": 5, "dietaryFiber": 0, "groups": ["dairy-products"], "image": null, "saturatedFat": 0 }, { "energeticValue": 18.6, "showIn": ["recipes", "menu"], "position": 3, "transFats": 0, "totalPortion": 20, "totalFat": 0.4, "saturatedFat": 0, "totalCarbohydrates": 0.4, "id": "qQNih", "dietaryFiber": 0, "addedSugars": 0, "groups": ["pork"], "totalSugars": 0, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "portionIncrement": 20, "sodium": 207.8, "proteins": 2.8, "portionMax": 80, "title": "Presunto magro", "type": "protein" }], "restrictions": ["celiac", "irritable", "intolerant", "ovovegetarian", "vegan", "allergic", "ovolactovegetarian", "lactovegetarian"], "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "favorited": null, "image": null },
    { "id": "2Z2UJ", "title": "Tapioca de queijo minas", "totalPortion": 70, "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "image": null, "ingredientsIds": ["7V3Ll", "zDJLW"], "favorited": null, "description": "Aqueça a tapioca em uma frigideira até ficar crocante, Coloque queijo minas frescal sobre metade da tapioca, Dobre a tapioca ao meio, Aqueça até o queijo derreter.", "ingredients": [{ "transFats": 0, "groups": ["cassava"], "saturatedFat": 0, "type": "carbo", "position": 1, "sodium": 0, "portionIncrement": 5, "totalFat": 0, "showIn": ["recipes", "menu"], "totalPortion": 50, "portionMax": 999, "title": "Tapioca", "totalCarbohydrates": 28, "energeticValue": 112, "favorited": null, "dietaryFiber": 0, "addedSugars": 0, "proteins": 0, "image": null, "totalSugars": 0, "restrictions": [], "id": "7V3Ll" }, { "proteins": 3.4, "id": "zDJLW", "type": "protein", "portionIncrement": 20, "groups": ["dairy-products"], "totalSugars": 0, "position": 2, "totalFat": 4, "portionMax": 100, "totalCarbohydrates": 0.6, "energeticValue": 52.8, "transFats": 0, "totalPortion": 20, "sodium": 6.2, "saturatedFat": 0, "favorited": null, "image": null, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "showIn": ["recipes"], "dietaryFiber": 0, "title": "Queijo minas frescal", "addedSugars": 0 }] },
    { "id": "59ALv", "title": "Tapioca de frango desfiado com margarina", "totalPortion": 75, "description": "Aqueça a tapioca em uma frigideira até ficar crocante, Coloque o peito de frango desfiado sobre metade da tapioca, Adicione um pouco de margarina sem sal sobre o frango, Dobre a tapioca ao meio, Aqueça até o recheio estar aquecido.", "ingredientsIds": ["7V3Ll", "4TdSD", "DvlwI"], "usedIn": ["breakfast", "morning-snack", "snack", "supper"], "image": null, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian", "irritable"], "favorited": null, "ingredients": [{ "title": "Tapioca", "showIn": ["recipes", "menu"], "position": 1, "groups": ["cassava"], "totalFat": 0, "dietaryFiber": 0, "addedSugars": 0, "proteins": 0, "restrictions": [], "favorited": null, "image": null, "sodium": 0, "energeticValue": 112, "portionMax": 999, "id": "7V3Ll", "totalCarbohydrates": 28, "saturatedFat": 0, "transFats": 0, "type": "carbo", "totalPortion": 50, "portionIncrement": 5, "totalSugars": 0 }, { "totalFat": 0.6, "position": 2, "transFats": 0, "portionMax": 999, "saturatedFat": 0, "totalSugars": 0, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"], "groups": ["chicken"], "addedSugars": 0, "sodium": 7.2, "favorited": null, "type": "protein", "energeticValue": 32.4, "title": "Peito de frango desfiado", "proteins": 6.2, "totalPortion": 20, "portionIncrement": 5, "dietaryFiber": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "image": null, "id": "4TdSD", "totalCarbohydrates": 0 }, { "type": "fat", "addedSugars": 0, "dietaryFiber": 0, "sodium": 3.85, "id": "DvlwI", "portionMax": 20, "groups": ["margarine"], "proteins": 0, "saturatedFat": 0, "title": "Margarina sem sal (80% de lipídeos)", "transFats": 0, "energeticValue": 36.1, "showIn": ["recipes"], "totalFat": 4.05, "restrictions": ["irritable"], "totalCarbohydrates": 0, "totalSugars": 0, "position": 3, "portionIncrement": 1, "totalPortion": 5 }] }
];

export const INGREDIENTS = [
    { "id": "bBxfW", "title": "Acelga, crua", "energeticValue": 20, "saturatedFat": 0, "dietaryFiber": 1, "groups": ["green-salad"], "transFats": 0, "showIn": ["recipes"], "totalFat": 0, "restrictions": [], "sodium": 1, "proteins": 1, "totalSugars": 0, "type": "salad", "totalCarbohydrates": 4, "totalPortion": 100, "addedSugars": 0 },
    { "id": "hbayC", "title": "Achocolatado em pó", "type": "protein", "totalFat": 2, "transFats": 0, "totalSugars": 0, "addedSugars": 0, "proteins": 4, "groups": ["dairy-products"], "showIn": ["recipes"], "sodium": 64, "dietaryFiber": 3, "energeticValue": 401, "totalPortion": 100, "totalCarbohydrates": 91, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "saturatedFat": 0 },
    { "id": "dZxqA", "title": "Acém bovino cozido moído", "totalFat": 10, "totalPortion": 100, "proteins": 26, "type": "protein", "addedSugars": 0, "energeticValue": 212, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "transFats": 0, "totalSugars": 0, "groups": ["beef"], "sodium": 52, "totalCarbohydrates": 0, "dietaryFiber": 0, "showIn": ["recipes", "menu"], "saturatedFat": 0 },
    { "id": "Puf4T", "title": "Acém bovino cozido sem gordura", "totalCarbohydrates": 0, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalPortion": 100, "totalFat": 10, "showIn": ["menu", "lunch", "dinner", "recipes"], "saturatedFat": 0, "dietaryFiber": 0, "energeticValue": 214, "totalSugars": 0, "groups": ["beef"], "sodium": 56, "transFats": 0, "addedSugars": 0, "type": "protein", "proteins": 27 },
    { "id": "PfwV9", "title": "Alface, americana, crua", "image": null, "transFats": 0, "type": "salad", "totalCarbohydrates": 1, "totalFat": 0, "addedSugars": 0, "totalPortion": 100, "energeticValue": 8, "saturatedFat": 0, "restrictions": [], "groups": ["green-salad"], "proteins": 0, "totalSugars": 0, "favorited": null, "showIn": ["recipes"], "dietaryFiber": 1, "sodium": 7 },
    { "id": "mNfLL", "title": "Alface, roxa, crua", "transFats": 0, "groups": ["purple-salad"], "totalSugars": 0, "favorited": null, "sodium": 7, "image": null, "restrictions": [], "dietaryFiber": 2, "energeticValue": 12, "totalPortion": 100, "saturatedFat": 0, "proteins": 0, "addedSugars": 0, "showIn": ["recipes"], "totalFat": 0, "type": "salad", "totalCarbohydrates": 2 },
    { "id": "pTegi", "title": "Alho, cru", "type": "salad", "sodium": 5, "saturatedFat": 0, "energeticValue": 113, "totalFat": 0, "transFats": 0, "dietaryFiber": 4, "restrictions": ["irritable"], "totalCarbohydrates": 23, "totalPortion": 100, "showIn": ["recipes"], "totalSugars": 0, "groups": ["white-salad"], "addedSugars": 0, "proteins": 7 },
    { "id": "iqZ24", "title": "Almôndegas bovinas fritas", "totalFat": 15, "energeticValue": 271, "totalPortion": 100, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "groups": ["beef"], "type": "protein", "addedSugars": 0, "dietaryFiber": 0, "saturatedFat": 0, "proteins": 18, "showIn": ["recipes"], "sodium": 1030, "totalCarbohydrates": 14, "totalSugars": 0, "transFats": 0 },
    { "id": "0YGbt", "title": "Arroz branco cozido", "totalCarbohydrates": 28, "proteins": 2, "totalFat": 0, "type": "carbo", "totalSugars": 0, "totalPortion": 100, "image": null, "groups": ["rice"], "dietaryFiber": 1, "sodium": 1, "saturatedFat": 0, "favorited": null, "energeticValue": 128, "restrictions": [], "showIn": ["menu", "lunch", "dinner", "recipes"], "addedSugars": 0, "transFats": 0 },
    { "id": "dDXan", "title": "Arroz integral cozido", "restrictions": [], "favorited": null, "totalSugars": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "proteins": 2, "energeticValue": 123, "sodium": 1, "type": "carbo", "totalCarbohydrates": 25, "transFats": 0, "groups": ["rice"], "image": null, "addedSugars": 0, "totalFat": 1, "saturatedFat": 0, "dietaryFiber": 2, "totalPortion": 100 },
    { "id": "rRQRc", "title": "Apresuntado", "dietaryFiber": 0, "addedSugars": 0, "saturatedFat": 0, "showIn": ["recipes"], "totalSugars": 0, "image": null, "type": "protein", "totalPortion": 100, "favorited": null, "groups": ["pork"], "energeticValue": 128, "restrictions": ["irritable", "ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "proteins": 13, "sodium": 942, "totalCarbohydrates": 2, "totalFat": 6, "transFats": 0 },
    { "id": "9YnxE", "title": "Atum fresco cru", "energeticValue": 117, "totalPortion": 100, "type": "protein", "totalCarbohydrates": 0, "proteins": 25, "showIn": ["recipes"], "totalSugars": "", "sodium": 30, "saturatedFat": "", "dietaryFiber": "", "totalFat": 0, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "groups": ["fish-seafood"], "addedSugars": "", "transFats": "" },
    { "id": "6FToU", "title": "Azeite de oliva extra virgem", "dietaryFiber": 0, "saturatedFat": 0, "transFats": 0, "totalSugars": 0, "proteins": 0, "restrictions": [], "totalPortion": 100, "totalCarbohydrates": 0, "sodium": 0, "addedSugars": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "totalFat": 100, "favorited": null, "type": "fat", "groups": ["vegetable-oils"], "energeticValue": 884, "image": null },
    { "id": "ZlShG", "title": "Bacalhau salgado refogado", "totalCarbohydrates": 1, "groups": ["fish-seafood"], "showIn": ["recipes"], "dietaryFiber": 0, "proteins": 23, "transFats": 0, "totalFat": 3, "addedSugars": 0, "totalSugars": 0, "sodium": 1256, "energeticValue": 139, "saturatedFat": 0, "type": "protein", "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalPortion": 100 },
    { "id": "2FEKt", "title": "Banana maçã in natura", "addedSugars": "", "totalPortion": 100, "energeticValue": 86, "showIn": ["recipes"], "transFats": "", "totalFat": 0, "totalCarbohydrates": 22, "groups": ["fruit"], "restrictions": [], "sodium": "", "type": "fruit", "dietaryFiber": 2, "saturatedFat": "", "proteins": 1, "totalSugars": "" },
    { "id": "voWmR", "title": "Batata baroa cozida", "totalPortion": 100, "showIn": ["menu", "lunch", "dinner", "recipes"], "sodium": 2, "totalFat": 0, "image": null, "totalCarbohydrates": 18, "groups": ["potato"], "energeticValue": 80, "favorited": null, "restrictions": [], "saturatedFat": 0, "dietaryFiber": 1, "proteins": 0, "type": "carbo", "transFats": 0, "totalSugars": 0, "addedSugars": 0, },
    { "id": "nnKtg", "title": "Batata inglesa cozida", "image": null, "sodium": 2, "addedSugars": 0, "type": "carbo", "totalSugars": 0, "totalFat": 0, "totalPortion": 100, "proteins": 1, "dietaryFiber": 1, "totalCarbohydrates": 11, "saturatedFat": 0, "energeticValue": 51, "restrictions": [], "groups": ["potato"], "transFats": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "favorited": null },
    { "id": "0H57f", "title": "Beterraba, cozida", "dietaryFiber": 1, "energeticValue": 32, "totalCarbohydrates": 7, "restrictions": ["irritable"], "sodium": 22, "addedSugars": 0, "groups": ["purple-salad"], "transFats": 0, "proteins": 1, "totalFat": 0, "showIn": ["recipes"], "totalPortion": 100, "type": "salad", "saturatedFat": 0, "totalSugars": 0 },
    { "id": "gI0SK", "title": "Bisteca de porco grelhada", "type": "protein", "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "saturatedFat": 0, "showIn": ["recipes", "menu"], "groups": ["pork"], "totalCarbohydrates": 0, "dietaryFiber": 0, "totalFat": 17, "energeticValue": 280, "totalPortion": 100, "sodium": 51, "totalSugars": 0, "transFats": 0, "proteins": 28, "addedSugars": 0 },
    { "id": "CDmOr", "title": "Brócolis, cozido", "restrictions": ["irritable"], "type": "salad", "showIn": ["recipes"], "groups": ["green-salad"], "totalFat": 0, "dietaryFiber": 3, "energeticValue": 24, "sodium": 2, "totalSugars": 0, "saturatedFat": 0, "totalPortion": 100, "transFats": 0, "totalCarbohydrates": 4, "addedSugars": 0, "proteins": 2 },
    { "id": "aSyR2", "title": "Camarão cozido", "totalCarbohydrates": 0, "saturatedFat": 0, "proteins": 18, "energeticValue": 90, "sodium": 366, "dietaryFiber": 0, "transFats": 0, "totalFat": 1, "type": "protein", "showIn": ["recipes", "menu"], "totalPortion": 100, "totalSugars": 0, "groups": ["fish-seafood"], "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "addedSugars": 0 },
    { "id": "K4VV3", "title": "Carne moída cozida", "image": null, "transFats": "", "groups": ["beef"], "energeticValue": 219, "proteins": 35, "addedSugars": "", "dietaryFiber": "", "sodium": "", "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"], "totalPortion": 100, "totalSugars": "", "type": "protein", "saturatedFat": "", "totalCarbohydrates": 0, "favorited": null, "totalFat": 7, "showIn": ["menu", "lunch", "dinner", "recipes"] },
    { "id": "m2EXe", "title": "Chocolate ao leite", "dietaryFiber": 2, "type": "protein", "totalFat": 30, "transFats": 0, "energeticValue": 539, "totalPortion": 100, "sodium": 77, "totalSugars": 0, "saturatedFat": 0, "groups": ["dairy-products"], "restrictions": ["celiac", "irritable", "intolerant", "ovovegetarian", "vegan"], "proteins": 7, "addedSugars": 0, "showIn": ["recipes"], "totalCarbohydrates": 59 },
    { "id": "XgEWu", "title": "Chuchu, cozido", "totalPortion": 100, "sodium": 1, "energeticValue": 18, "dietaryFiber": 1, "totalCarbohydrates": 4, "saturatedFat": 0, "proteins": 0, "totalSugars": 0, "groups": ["green-salad"], "restrictions": [], "type": "salad", "showIn": ["recipes"], "transFats": 0, "totalFat": 0, "addedSugars": 0 },
    { "id": "ofHMX", "title": "Contra-filé bovino grelhado com gordura", "showIn": ["recipes", "menu"], "dietaryFiber": 0, "groups": ["beef"], "proteins": 32, "saturatedFat": 0, "addedSugars": 0, "totalSugars": 0, "type": "protein", "sodium": 57, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalPortion": 100, "energeticValue": 278, "totalFat": 15, "transFats": 0, "totalCarbohydrates": 0 },
    { "id": "q9AK9", "title": "Contra-filé de costela bovino grelhado", "totalPortion": 100, "totalCarbohydrates": 0, "addedSugars": 0, "type": "protein", "totalFat": 16, "groups": ["beef"], "energeticValue": 274, "showIn": ["recipes", "menu"], "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "saturatedFat": 0, "transFats": 0, "dietaryFiber": 0, "totalSugars": 0, "proteins": 29, "sodium": 50 },
    { "id": "I3D8T", "title": "Couve-flor, cozida", "totalCarbohydrates": 3, "transFats": 0, "sodium": 1, "type": "salad", "addedSugars": 0, "energeticValue": 19, "totalPortion": 100, "showIn": ["recipes"], "totalFat": 0, "totalSugars": 0, "dietaryFiber": 2, "saturatedFat": 0, "proteins": 1, "restrictions": [], "groups": ["white-salad"] },
    { "id": "Tqbns", "title": "Coxa de frango cozida sem pele ", "energeticValue": 167, "totalPortion": 100, "totalCarbohydrates": 0, "totalSugars": 0, "proteins": 26, "showIn": ["recipes", "menu"], "totalFat": 5, "transFats": 0, "dietaryFiber": 0, "saturatedFat": 0, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "groups": ["chicken"], "type": "protein", "addedSugars": 0, "sodium": 64 },
    { "id": "ap5F3", "title": "Coxinha de frango, frita", "totalSugars": "", "dietaryFiber": 4, "proteins": 9, "showIn": [], "totalCarbohydrates": 34, "restrictions": [], "energeticValue": 283, "groups": ["beef"], "transFats": "", "sodium": 532, "type": "protein", "totalPortion": 100, "totalFat": 11, "addedSugars": "", "saturatedFat": "" },
    { "id": "ip60q", "title": "Coxão mole bovino cozido sem gordura", "energeticValue": 218, "addedSugars": 0, "showIn": ["recipes", "menu"], "transFats": 0, "type": "protein", "totalPortion": 100, "sodium": 43, "groups": ["beef"], "totalCarbohydrates": 0, "dietaryFiber": 0, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalFat": 8, "saturatedFat": 0, "totalSugars": 0, "proteins": 32 },
    { "id": "76WQW", "title": "Cupim bovino assado", "energeticValue": 330, "transFats": 0, "showIn": ["recipes", "menu"], "sodium": 71, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "addedSugars": 0, "proteins": 28, "totalCarbohydrates": 0, "dietaryFiber": 0, "totalPortion": 100, "type": "protein", "totalFat": 23, "saturatedFat": 0, "groups": ["beef"], "totalSugars": 0 },
    { "id": "tDTwq", "title": "Doce goiaba em pasta", "totalCarbohydrates": 74, "proteins": 0, "addedSugars": "", "totalSugars": "", "transFats": "", "sodium": 3, "energeticValue": 268, "showIn": ["recipes"], "saturatedFat": "", "restrictions": [], "type": "fruit", "totalPortion": 100, "totalFat": 0, "dietaryFiber": 3, "groups": ["fruit"] },
    { "id": "TaDFX", "title": "Ervilha em vagem", "saturatedFat": 0, "proteins": 7, "energeticValue": 88, "groups": ["peas"], "type": "carbo", "totalPortion": 100, "transFats": 0, "showIn": ["recipes", "menu"], "sodium": 0, "totalFat": 0, "addedSugars": 0, "totalSugars": 0, "restrictions": [], "dietaryFiber": 9, "totalCarbohydrates": 14 },
    { "id": "sy7s0", "title": "Farinha de mandioca crua", "dietaryFiber": 6, "sodium": 1, "totalPortion": 100, "proteins": 1, "restrictions": [], "totalSugars": "", "transFats": "", "totalCarbohydrates": 87, "groups": ["cassava"], "addedSugars": "", "saturatedFat": "", "energeticValue": 360, "showIn": ["recipes"], "totalFat": 0, "type": "carbo" },
    { "id": "E9ojj", "title": "Feijão carioca cozido", "sodium": 1, "groups": ["beans"], "addedSugars": 0, "dietaryFiber": 8, "transFats": 0, "totalSugars": 0, "totalPortion": 100, "totalFat": 0, "type": "carbo", "proteins": 4, "saturatedFat": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "totalCarbohydrates": 13, "energeticValue": 76, "image": null, "favorited": null, "restrictions": ["irritable"] },
    { "id": "dtgmn", "title": "Feijão fradinho cozido", "proteins": 5, "sodium": 0, "energeticValue": 78, "transFats": 0, "totalSugars": 0, "totalPortion": 100, "addedSugars": 0, "groups": ["beans"], "dietaryFiber": 7, "showIn": ["recipes", "menu"], "restrictions": ["irritable"], "type": "carbo", "saturatedFat": 0, "totalCarbohydrates": 13, "totalFat": 0 },
    { "id": "yp22f", "title": "Feijão preto  cozido", "showIn": ["menu", "lunch", "dinner", "recipes"], "totalSugars": 0, "totalCarbohydrates": 14, "saturatedFat": 0, "energeticValue": 77, "restrictions": ["irritable"], "dietaryFiber": 8, "addedSugars": 0, "transFats": 0, "totalPortion": 100, "type": "carbo", "image": null, "groups": ["beans"], "proteins": 4, "totalFat": 0, "sodium": 1, "favorited": null },
    { "id": "kEwAV", "title": "Filé de abadejo assado", "groups": ["fish-seafood"], "totalFat": 1, "type": "protein", "totalPortion": 100, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "dietaryFiber": 0, "sodium": 334, "totalSugars": 0, "transFats": 0, "saturatedFat": 0, "showIn": ["menu"], "addedSugars": 0, "energeticValue": 111, "totalCarbohydrates": 0, "proteins": 23 },
    { "id": "KAq8r", "title": "Frango, asa, com pele, crua", "totalPortion": 100, "dietaryFiber": "", "proteins": 18, "type": "protein", "groups": ["chicken"], "transFats": "", "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalFat": 15, "sodium": 96, "totalCarbohydrates": 0, "energeticValue": 213, "showIn": ["recipes"], "addedSugars": "", "saturatedFat": "", "totalSugars": "" },
    { "id": "xaPCt", "title": "Frango, inteiro, sem pele, cru", "dietaryFiber": "", "saturatedFat": "", "proteins": 20, "totalSugars": "", "totalCarbohydrates": 0, "totalFat": 4, "showIn": [], "transFats": "", "energeticValue": 129, "type": "protein", "addedSugars": "", "sodium": 72, "restrictions": [], "groups": ["chicken"], "totalPortion": 100 },
    { "id": "Dkmf1", "title": "Fígado bovino grelhado", "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalFat": 9, "showIn": ["recipes", "menu"], "saturatedFat": 0, "totalPortion": 100, "type": "protein", "dietaryFiber": 0, "groups": ["beef"], "sodium": 82, "totalSugars": 0, "addedSugars": 0, "totalCarbohydrates": 4, "proteins": 29, "transFats": 0, "energeticValue": 225 },
    { "id": "SiNIi", "title": "Granola", "sodium": 125, "proteins": 11, "groups": [], "transFats": "", "favorited": null, "totalCarbohydrates": 62.5, "totalFat": 12.5, "showIn": ["menu", "lunch", "dinner", "recipes"], "type": "carbo", "energeticValue": 407.5, "restrictions": ["celiac"], "saturatedFat": 3.5, "dietaryFiber": "", "image": null, "totalSugars": "", "addedSugars": "", "totalPortion": 100 },
    { "id": "koAYe", "title": "Iogurte natural desnatado", "totalFat": 0, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "energeticValue": 32, "saturatedFat": 0, "totalCarbohydrates": 4, "addedSugars": 0, "transFats": 0, "showIn": ["recipes"], "type": "protein", "totalPortion": 100, "groups": ["dairy-products"], "proteins": 3, "sodium": 59, "dietaryFiber": 0, "totalSugars": 0, },
    { "id": "bSZyM", "title": "Lagarto bovino cozido", "type": "protein", "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "groups": ["beef"], "totalPortion": 100, "proteins": 32, "sodium": 47, "energeticValue": 222, "dietaryFiber": 0, "showIn": ["recipes", "menu"], "transFats": 0, "totalSugars": 0, "totalCarbohydrates": 0, "addedSugars": 0, "totalFat": 9, "saturatedFat": 0 },
    { "id": "BU6jA", "title": "Leite de vaca desnatado ", "saturatedFat": 0, "totalPortion": 100, "proteins": 2, "totalSugars": 0, "type": "protein", "dietaryFiber": 0, "sodium": 51, "energeticValue": 31, "groups": ["dairy-products"], "transFats": 0, "totalFat": 0, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "totalCarbohydrates": 5, "showIn": ["recipes"], "addedSugars": 0 },
    { "id": "WBusq", "title": "Leite de vaca integral", "proteins": 2, "dietaryFiber": "", "totalFat": 3, "transFats": "", "saturatedFat": "", "groups": ["dairy-products"], "totalSugars": "", "totalCarbohydrates": 5, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "type": "protein", "totalPortion": 100, "addedSugars": "", "showIn": ["recipes"], "sodium": 63, "energeticValue": 58 },
    { "id": "kKmcg", "title": "Lombo de porco assado", "proteins": 35, "dietaryFiber": 0, "totalCarbohydrates": 0, "energeticValue": 210, "totalPortion": 100, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "transFats": 0, "saturatedFat": 0, "addedSugars": 0, "totalFat": 6, "type": "protein", "showIn": ["menu", "lunch", "dinner", "recipes"], "totalSugars": 0, "favorited": null, "sodium": 38, "image": null, "groups": ["pork"] },
    { "id": "sMj1c", "title": "Macarrão cozido", "type": "carbo", "groups": ["pasta"], "favorited": null, "totalFat": 0.9, "proteins": 5.8, "transFats": "", "addedSugars": "", "totalSugars": "", "saturatedFat": 0.2, "totalCarbohydrates": 30.9, "energeticValue": 158, "sodium": 0, "image": null, "restrictions": ["diabetic", "vegan", "lactovegetarian", "celiac"], "showIn": ["menu", "lunch", "dinner", "recipes"], "dietaryFiber": 1.8, "totalPortion": 100 },
    { "id": "EALbW", "title": "Ovo de galinha inteiro frito", "restrictions": ["lactovegetarian", "vegan"], "dietaryFiber": 0, "totalFat": 18, "totalCarbohydrates": 1, "addedSugars": 0, "totalSugars": 0, "energeticValue": 240, "totalPortion": 100, "showIn": ["recipes"], "saturatedFat": 0, "favorited": null, "groups": ["eggs-and-derivatives"], "type": "protein", "transFats": 0, "sodium": 166, "image": null, "proteins": 15 },
    { "id": "4TdSD", "title": "Peito de frango desfiado", "energeticValue": 162, "sodium": 36, "favorited": null, "proteins": 31, "totalSugars": 0, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"], "image": null, "totalCarbohydrates": 0, "totalPortion": 100, "groups": ["chicken"], "dietaryFiber": 0, "addedSugars": 0, "type": "protein", "saturatedFat": 0, "totalFat": 3, "transFats": 0, "showIn": ["menu", "lunch", "dinner", "recipes"] },
    { "id": "CRt5Y", "title": "Pernil de porco assado", "showIn": ["recipes", "menu"], "transFats": 0, "favorited": null, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "proteins": 32, "totalPortion": 100, "saturatedFat": 0, "type": "protein", "totalCarbohydrates": 0, "image": null, "groups": ["pork"], "sodium": 62, "energeticValue": 262, "addedSugars": 0, "totalSugars": 0, "dietaryFiber": 0, "totalFat": 13 },
    { "id": "jor1V", "title": "Picanha bovina crua sem gordura", "addedSugars": "", "saturatedFat": "", "groups": ["beef"], "totalPortion": 100, "totalCarbohydrates": 0, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "totalSugars": "", "energeticValue": 133, "showIn": ["recipes"], "type": "protein", "dietaryFiber": "", "transFats": "", "proteins": 21, "sodium": 61, "totalFat": 4 },
    { "id": "UissS", "title": "Polenta cozida", "totalFat": 0, "showIn": ["menu", "lunch", "dinner", "recipes"], "restrictions": [], "image": null, "proteins": 2, "totalPortion": 100, "totalSugars": 0, "totalCarbohydrates": 23, "type": "carbo", "favorited": null, "transFats": 0, "dietaryFiber": 2, "groups": ["corn"], "addedSugars": 0, "sodium": 441, "energeticValue": 102, "saturatedFat": 0 },
    { "id": "vuRQG", "title": "Pão de forma", "dietaryFiber": 6, "sodium": 506, "energeticValue": 253, "totalSugars": "", "favorited": null, "totalPortion": 100, "transFats": "", "groups": ["bread"], "totalCarbohydrates": 49, "proteins": 9, "image": null, "totalFat": 3, "type": "carbo", "showIn": ["recipes"], "saturatedFat": "", "addedSugars": "", "restrictions": ["celiac", "irritable"] },
    { "id": "5QTtj", "title": "Pão francês", "totalCarbohydrates": 58, "totalPortion": 100, "energeticValue": 299, "transFats": "", "image": null, "groups": ["bread"], "proteins": 7, "sodium": 647, "restrictions": ["celiac", "irritable", "lactovegetarian", "vegan"], "totalSugars": "", "addedSugars": "", "showIn": ["recipes"], "type": "carbo", "dietaryFiber": 2, "favorited": null, "saturatedFat": "", "totalFat": 3 },
    { "id": "Jy1M8", "title": "Queijo cottage", "dietaryFiber": "", "favorited": null, "proteins": 11.6, "image": null, "totalFat": 3.6, "sodium": 362, "transFats": "", "restrictions": ["allergic", "intolerant", "vegan", "ovovegetarian", "irritable"], "saturatedFat": 1.1, "showIn": ["recipes"], "groups": ["dairy-products"], "addedSugars": "", "type": "protein", "totalCarbohydrates": 2.6, "totalSugars": "", "totalPortion": 100, "energeticValue": 90 },
    { "id": "zDJLW", "title": "Queijo minas frescal", "showIn": ["recipes"], "totalPortion": 100, "groups": ["dairy-products"], "totalFat": 20, "favorited": null, "transFats": 0, "type": "protein", "proteins": 17, "saturatedFat": 0, "image": null, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "energeticValue": 264, "addedSugars": 0, "totalSugars": 0, "dietaryFiber": 0, "totalCarbohydrates": 3, "sodium": 31, },
    { "id": "nZesb", "title": "Queijo minas meia cura", "transFats": 0, "totalCarbohydrates": 3, "energeticValue": 320, "totalSugars": 0, "showIn": ["recipes"], "totalFat": 24, "saturatedFat": 0, "type": "protein", "groups": ["dairy-products"], "restrictions": ["intolerant", "ovovegetarian", "vegan"], "proteins": 21, "sodium": 501, "dietaryFiber": 0, "addedSugars": 0, "totalPortion": 100, },
    { "id": "9pnLo", "title": "Queijo mussarela", "proteins": 22, "totalPortion": 100, "type": "protein", "addedSugars": 0, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan", "allergic"], "favorited": null, "showIn": ["recipes"], "sodium": 581, "totalCarbohydrates": 3, "totalSugars": 0, "totalFat": 25, "saturatedFat": 0, "transFats": 0, "groups": ["dairy-products"], "energeticValue": 329, "dietaryFiber": 0, "image": null },
    { "id": "51IhN", "title": "Queijo parmesão", "groups": ["dairy-products"], "transFats": 0, "showIn": ["recipes"], "dietaryFiber": 0, "totalFat": 33, "totalPortion": 100, "totalCarbohydrates": 1, "saturatedFat": 0, "type": "protein", "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "addedSugars": 0, "totalSugars": 0, "energeticValue": 452, "sodium": 1844, "proteins": 35 },
    { "id": "26qKW", "title": "Queijo prato", "transFats": 0, "totalPortion": 100, "showIn": ["recipes"], "type": "protein", "saturatedFat": 0, "addedSugars": 0, "totalCarbohydrates": 1, "groups": ["dairy-products"], "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "proteins": 22, "totalFat": 29, "dietaryFiber": 0, "totalSugars": 0, "energeticValue": 359, "sodium": 579 },
    { "id": "g2XYY", "title": "Requeijão cremoso", "dietaryFiber": "", "addedSugars": "", "totalPortion": 100, "proteins": 9, "energeticValue": 256, "restrictions": ["irritable", "intolerant", "ovovegetarian", "vegan"], "transFats": "", "totalCarbohydrates": 2, "saturatedFat": "", "sodium": 557, "totalFat": 23, "showIn": ["recipes"], "type": "protein", "groups": ["dairy-products"], "totalSugars": "" },
    { "id": "BTRCw", "title": "Sardinha assada", "totalSugars": 0, "energeticValue": 164, "type": "protein", "favorited": null, "totalPortion": 100, "showIn": ["menu", "lunch", "dinner", "recipes"], "transFats": 0, "restrictions": ["ovolactovegetarian", "lactovegetarian", "ovovegetarian", "vegan"], "sodium": 74, "groups": ["fish-seafood"], "image": null, "dietaryFiber": 0, "proteins": 32, "totalCarbohydrates": 0, "saturatedFat": 0, "totalFat": 2, "addedSugars": 0 },
    { "id": "7V3Ll", "title": "Tapioca", "transFats": 0, "groups": ["cassava"], "totalPortion": 100, "totalCarbohydrates": 56, "sodium": 0, "totalFat": 0, "dietaryFiber": 0, "image": null, "totalSugars": 0, "favorited": null, "restrictions": [], "energeticValue": 224, "type": "carbo", "proteins": 0, "addedSugars": 0, "saturatedFat": 0, "showIn": ["recipes", "menu"] },
    { "id": "OaQfp", "title": "Tilápia cozida", "saturatedFat": 0.9, "addedSugars": 0, "favorited": null, "sodium": 0, "type": "protein", "energeticValue": 128, "totalSugars": 0, "groups": ["turkey"], "image": null, "showIn": ["menu", "lunch", "dinner", "recipes"], "dietaryFiber": 0, "totalPortion": 100, "totalCarbohydrates": 0, "proteins": 26.2, "transFats": 0, "totalFat": 2.3, "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"] },
    { "id": "gt6GW", "title": "Tomate, salada", "energeticValue": 20, "totalCarbohydrates": 5, "dietaryFiber": 2, "type": "salad", "sodium": 5, "saturatedFat": 0, "totalPortion": 100, "totalSugars": 0, "restrictions": [], "proteins": 0, "transFats": 0, "totalFat": 0, "addedSugars": 0, "showIn": ["recipes"], "groups": ["red-salad"] },
    { "id": "looWL", "title": "Óleo de soja", "showIn": ["recipes"], "groups": ["vegetable-oils"], "totalFat": 100, "totalPortion": 100, "totalSugars": 0, "transFats": 0, "restrictions": [], "totalCarbohydrates": 0, "energeticValue": 884, "favorited": null, "sodium": 0, "proteins": 0, "dietaryFiber": 0, "type": "fat", "image": null, "saturatedFat": 0, "addedSugars": 0 },
    { "id": "fjOoN", "title": "Óleo de linhaça", "showIn": ["recipes"], "energeticValue": 900, "proteins": 0, "favorited": null, "saturatedFat": 10, "totalPortion": 100, "transFats": 0, "sodium": 0, "dietaryFiber": 0, "restrictions": [], "image": null, "groups": ["flaxseed"], "addedSugars": 0, "totalCarbohydrates": 0, "totalSugars": 0, "type": "fat", "totalFat": 100 }
];

export const INGREDIENT_GROUPS = [
    { "id": "13bR2", "type": "fat", "title": "Amendoim", "slug": "peanut", "restrictions": [] },
    { "id": "MvdDz", "title": "Arroz", "slug": "rice", "type": "carbo", "restrictions": [] },
    { "id": "CL7sT", "type": "carbo", "slug": "oats", "title": "Aveia", "restrictions": [] },
    { "id": "ZDiab", "type": "fat", "slug": "vegetable-oils", "title": "Azeite de oliva e óleos", "restrictions": [] },
    { "id": "TSCUC", "slug": "potato", "title": "Batata inglesa/doce", "type": "carbo", "restrictions": [] },
    { "id": "x1RAE", "type": "protein", "slug": "beef", "title": "Carne Bovina", "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"] },
    { "id": "SQB0U", "slug": "pork", "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"], "type": "protein", "title": "Carne de Porco" },
    { "id": "6QPlZ", "title": "Carne de frango", "slug": "chicken", "type": "protein", "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"] },
    { "id": "7oLJx", "type": "fat", "title": "Castanhas", "slug": "nuts", "restrictions": [] },
    { "id": "IWZbg", "title": "Feijão", "type": "protein", "slug": "beans", "restrictions": ["irritable"] },
    { "id": "j42Bx", "slug": "fruit", "title": "Fruta", "type": "fruit", "restrictions": [] },
    { "id": "B3oku", "slug": "dairy-products", "title": "Leites e derivados", "type": "protein", "restrictions": ["vegan", "ovovegetarian", "irritable"] },
    { "id": "LrUWp", "type": "carbo", "slug": "cassava", "title": "Mandioca/Aipim/Macaxeira", "restrictions": [] },
    { "id": "wOpyj", "slug": "margarine", "type": "fat", "title": "Margarina", "restrictions": [] },
    { "id": "FjtHg", "title": "Massa", "slug": "pasta", "type": "carbo", "restrictions": [] },
    { "id": "Q28R3", "title": "Milho", "type": "carbo", "slug": "corn", "restrictions": [] },
    { "id": "X5AU1", "title": "Nozes", "slug": "walnuts", "type": "fat" }, { "slug": "others", "title": "Outros", "type": "other", "id": "qRIXyVbGrMk7GR6gkVX0", "restrictions": [] },
    { "id": "ugjGw", "title": "Ovos e derivados", "slug": "eggs-and-derivatives", "type": "protein", "restrictions": ["vegan", "lactovegetarian"] },
    { "id": "NSwZC", "slug": "fish-seafood", "type": "protein", "title": "Peixes/Frutos do mar", "restrictions": ["vegan", "ovolactovegetarian", "ovovegetarian", "lactovegetarian"] },
    { "id": "mrNzJ", "slug": "bread", "type": "carbo", "title": "Pão", "restrictions": ["irritable", "vegan"] },
    { "id": "yATSE", "title": "Salada Amarela", "slug": "yellow-orange-salad", "type": "salad" },
    { "id": "ibl2G", "slug": "purple-salad", "title": "Salada Roxa", "type": "salad", "restrictions": [] },
    { "id": "UVeK6", "slug": "green-salad", "type": "salad", "title": "Salada Verde", "restrictions": [] },
    { "id": "5WiSo", "title": "Salada Vermelha", "slug": "red-salad", "type": "salad", "restrictions": [] },
    { "id": "VxkLG", "title": "Soja", "type": "carbo", "slug": "soy", "restrictions": [] },
];

export const PARTNERS = [
    {
        "id": "FHNss",
        "coupon": "#academiaextreme",
        "title": "Academia Extreme",
        "registerDate": new Date('2023-03-10'),
    }, {
        "id": "Zvma7",
        "coupon": "#academiaproactive",
        "title": "Academia Proactive",
        "registerDate": new Date('2023-03-10'),
    }, {
        "id": "9GHTz",
        "title": "Academia Suprema",
        "coupon": "#academiasuprema",
        "registerDate": new Date('2023-03-12'),
    }, {
        "id": "kQKV3",
        "title": "Academia Vitalidade",
        "coupon": "#academiavitalidade",
        "registerDate": new Date('2023-04-13'),
    }, {
        "id": "Dhxg1",
        "coupon": "#atitudesaúde",
        "title": "Atitude Saúde",
        "registerDate": new Date('2023-06-28'),
    }, {
        "id": "882BV",
        "coupon": "#corpoemmovimento",
        "title": "Corpo em Movimento",
        "registerDate": new Date('2023-07-30'),
    }, {
        "id": "GVoKU",
        "coupon": "#elitefitness",
        "title": "Elite Fitness",
        "registerDate": new Date('2023-07-31'),
    }, {
        "id": "yURsn",
        "title": "Energia Ativa",
        "coupon": "#energiaativa",
        "registerDate": new Date('2023-09-10'),
    }, {
        "id": "f3eIK",
        "coupon": "#evoluçãofitness",
        "title": "Evolução Fitness",
        "registerDate": new Date('2023-10-29'),
    }, {
        "id": "75QKX",
        "coupon": "#fitnesstotal",
        "title": "Fitness Total",
        "registerDate": new Date('2023-11-14'),
    }, {
        "id": "LbjpF",
        "title": "Forma Física Completa",
        "coupon": "#formafísicacompleta",
        "registerDate": new Date('2023-12-10'),
    }, {
        "id": "xjyv0",
        "coupon": "#impactofitness",
        "title": "Impacto Fitness",
        "registerDate": new Date('2024-02-12'),
    }, {
        "id": "pxfdH",
        "title": "Movimento Natural",
        "coupon": "#movimentonatural",
        "registerDate": new Date('2024-03-10'),
    }, {
        "id": "HPNL2",
        "coupon": "#powerzoneacademia",
        "title": "PowerZone Academia",
        "registerDate": new Date('2024-04-21'),
    }, {
        "id": "nXOme",
        "coupon": "#smartfitassisbrasil",
        "title": "Smart Fit Assis Brasil",
        "registerDate": new Date('2024-04-20'),
    }, {
        "id": "AhrcP",
        "title": "Smart Fit Praia de Belas",
        "coupon": "#smartfitpraiadebelas",
        "registerDate": new Date('2024-04-24'),
    }, {
        "id": "QAz9b",
        "title": "Studio Treino",
        "coupon": "#studiotreino",
        "registerDate": new Date('2024-05-30'),
    }, {
        "id": "0CP7p",
        "title": "Vida em Equilíbrio",
        "coupon": "#vidaemequilíbrio",
        "registerDate": new Date('2024-06-07'),
    }
]

export const PRIVACY = [
    {
        "id": "0LE3SEABL7zgv2jUjJCU",
        "title": "Lorem ipsum dolor sit amet",
        "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius neque ac risus convallis scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut nunc id dolor finibus bibendum. Suspendisse sit amet elit vel ex feugiat bibendum. Sed vel eros id libero molestie pretium. Nulla a lorem euismod nulla varius dictum eu a urna. Maecenas pretium magna in facilisis lacinia. In hac habitasse platea dictumst. Sed vel ligula justo. Aenean non sagittis arcu. Vestibulum porttitor sit amet purus non tincidunt. <br><br> In hac habitasse platea dictumst. Etiam sed euismod turpis, eu vehicula erat. Phasellus sit amet ligula vitae lorem gravida dignissim sit amet ut purus. Sed lobortis auctor mi ac ullamcorper. Curabitur id dapibus elit. Curabitur ut hendrerit nisi, at tincidunt nibh. Sed nec malesuada leo. Nam aliquet suscipit massa, sit amet dapibus dui varius feugiat. Vivamus suscipit tristique tristique. Curabitur id risus non magna egestas suscipit.",
    },
    {
        "id": "OwVWyVzWF2OfeT4PgYg5",
        "title": "Lorem ipsum dolor sit amet",
        "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius neque ac risus convallis scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut nunc id dolor finibus bibendum. Suspendisse sit amet elit vel ex feugiat bibendum. Sed vel eros id libero molestie pretium. Nulla a lorem euismod nulla varius dictum eu a urna. Maecenas pretium magna in facilisis lacinia. In hac habitasse platea dictumst. Sed vel ligula justo. Aenean non sagittis arcu. Vestibulum porttitor sit amet purus non tincidunt. <br><br> In hac habitasse platea dictumst. Etiam sed euismod turpis, eu vehicula erat. Phasellus sit amet ligula vitae lorem gravida dignissim sit amet ut purus. Sed lobortis auctor mi ac ullamcorper. Curabitur id dapibus elit. Curabitur ut hendrerit nisi, at tincidunt nibh. Sed nec malesuada leo. Nam aliquet suscipit massa, sit amet dapibus dui varius feugiat. Vivamus suscipit tristique tristique. Curabitur id risus non magna egestas suscipit."
    }
];

export const TERMS = [
    {
        "id": "0LE3SEABL7zgv2jUjJCU",
        "title": "Lorem ipsum dolor sit amet",
        "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius neque ac risus convallis scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut nunc id dolor finibus bibendum. Suspendisse sit amet elit vel ex feugiat bibendum. Sed vel eros id libero molestie pretium. Nulla a lorem euismod nulla varius dictum eu a urna. Maecenas pretium magna in facilisis lacinia. In hac habitasse platea dictumst. Sed vel ligula justo. Aenean non sagittis arcu. Vestibulum porttitor sit amet purus non tincidunt. <br><br> In hac habitasse platea dictumst. Etiam sed euismod turpis, eu vehicula erat. Phasellus sit amet ligula vitae lorem gravida dignissim sit amet ut purus. Sed lobortis auctor mi ac ullamcorper. Curabitur id dapibus elit. Curabitur ut hendrerit nisi, at tincidunt nibh. Sed nec malesuada leo. Nam aliquet suscipit massa, sit amet dapibus dui varius feugiat. Vivamus suscipit tristique tristique. Curabitur id risus non magna egestas suscipit."
    }
]

export const USERS = [
    {
        "activityLevel": 0,
        "age": 22,
        "coins": 240,
        "preferences": [],
        "signature": {
            "gym": {
                "coupon": "#academiaextreme",
                "title": "Academia Extreme",
                "id": "FHNc8pOamgCwAfTd3Nss",
                "registerDate": new Date('2023-03-10'),
            },
            "plan": {
                "isClicked": false,
                "type": "Anual",
                "androidID": "br.com.nutri.pro@annual",
                "value": 350,
                "order": 0,
                "currency": "BRL",
                "id": "UBypfbni6c6YPWkiR6so",
                "description": "Nessa modalidade <b>uma vez ao ano</b> você paga:",
                "title": "Anual",
                "isTrial": false,
                "valid": true,
                "iosID": "br.com.nutri.pro.annual"
            }
        },
        "gender": "male",
        "uid": "559VoD86YnMC2kzqfZ38zBUwcO22",
        "id": "559VoD86YnMC2kzqfZ38zBUwcO22",
        "subscribe": {
            "sub_id": "sub_aMjZqGmTQTN1y7WO",
            "status": true,
            "date": { "seconds": 1718064000, "nanoseconds": 0 },
            "paymentType": "pagarme",
            "validity": { "seconds": 1749599999, "nanoseconds": 0 }
        },
        "get": 2512.5930150000004,
        "email": "teste@pwa.com",
        "level": 2,
        "name": "Carlos Henrique",
        "registerDate": new Date(),
        "restrictions": ["celiac", "intolerant"],
        "objective": 0,
        "role": "user",
        "height": 170,
        "mealsADay": 4,
        "weight": 78,
        "desiredWeight": 75,
        "desiredWeightLossByWeek": 0.4,
        "tmb": 1834.0095000000001
    },
    {
        "activityLevel": 2,
        "age": 30,
        "coins": 0,
        "gender": "male",
        "id": "2dc0n4W1OTXhb5L9wh2F7fHKs9H2",
        "get": 2028.7751999999998,
        "email": "rafael@rafaelabreu.eti.br",
        "level": 1,
        "name": "Rafael Abreu",
        "objective": 1,
        "height": 160,
        "mealsADay": 4,
        "desiredWeight": 55,
        "desiredWeightLossByWeek": 0.23,
        "preferences": [],
        "registerDate": new Date("2024-07-16"),
        "restrictions": ["irritable"],
        "role": "user",
        "signature": {
            "gym": {
                "id": "f3eO6JV6QgdfwSwW1MIK",
                "coupon": "#evoluçãofitness",
                "title": "Evolução Fitness",
                "registerDate": new Date('2023-10-29'),
            },
            "plan": {
                "isClicked": true,
                "type": "Mensal",
                "androidID": "br.com.nutri.pro@monthly",
                "value": 34.99,
                "order": 1,
                "currency": "BRL",
                "id": "o3IHVsbnyUg7NyzB1bAh",
                "description": "Nessa modalidade <b>mensalmente</b> você paga:",
                "title": "Mensal",
                "isTrial": true,
                "valid": true,
                "iosID": "my_product"
            }
        },
        "subscribe": {
            "paymentType": "android-playstore",
            "status": true,
            "validity": { "seconds": 1712773351, "nanoseconds": 428000000 },
            "date": { "seconds": 1712773059, "nanoseconds": 61000000 }
        },
        "tmb": 1690.646,
        "uid": "2dc0n4W1OTXhb5L9wh2F7fHKs9H2",
        "weight": 75,
    },
    {
        "activityLevel": 1,
        "age": 39,
        "coins": 98,
        "desiredWeight": null,
        "desiredWeightLossByWeek": null,
        "gender": "female",
        "id": "2law9d4h6Ieqi2xuF41g",
        "get": 1981.67349,
        "email": "maria@gmail.com",
        "level": 3,
        "objective": 1,
        "height": 168,
        "mealsADay": 4,
        "name": "Maria Carolina",
        "restrictions": ["vegan", "diabetic"],
        "registerDate": new Date("2024-10-16"),
        "preferences": null,
        "role": "admin",
        "signature": {
            "gym": {
                "id": "f3eO6JV6QgdfwSwW1MIK",
                "coupon": "#evoluçãofitness",
                "title": "Evolução Fitness",
                "registerDate": new Date('2023-10-29'),
            },
            "plan": null
        },
        "subscribe": null,
        "tmb": 1446.4769999999999,
        "uid": "2law9d4h6Ieqi2xuF41g",
        "weight": 70,
    },
    {
        "activityLevel": 1,
        "age": 26,
        "coins": 65,
        "gender": "male",
        "desiredWeight": null,
        "desiredWeightLossByWeek": null,
        "id": "5VNfwL2UXItJAHux06ap",
        "get": 1977.49362,
        "email": "tes_23@hotmail.com",
        "level": 8,
        "name": "Carlos Dias",
        "objective": 2,
        "height": 170,
        "mealsADay": 5,
        "weight": 69,
        "preferences": [],
        "registerDate": new Date("2024-10-14"),
        "restrictions": [],
        "role": "admin",
        "signature": {
            "gym": null,
            "plan": {
                "isClicked": true,
                "type": "Mensal",
                "androidID": "br.com.nutri.pro@monthly",
                "value": 34.99,
                "order": 1,
                "currency": "BRL",
                "id": "o3IHVsbnyUg7NyzB1bAh",
                "description": "Nessa modalidade <b>mensalmente</b> você paga:",
                "title": "Mensal",
                "isTrial": true,
                "valid": true,
                "iosID": "my_product"
            }
        },
        "subscribe": null,
        "uid": "5VNfwL2UXItJAHux06ap",
        "tmb": 1443.426
    },
    {
        "activityLevel": 0,
        "age": 31,
        "coins": 87,
        "preferences": [],
        "signature": {
            "gym": null,
            "plan": {
                "isClicked": false,
                "type": "Anual",
                "androidID": "br.com.nutri.pro@annual",
                "value": 350,
                "order": 0,
                "currency": "BRL",
                "id": "UBypfbni6c6YPWkiR6so",
                "description": "Nessa modalidade <b>uma vez ao ano</b> você paga:",
                "title": "Anual",
                "isTrial": false,
                "valid": true,
                "iosID": "br.com.nutri.pro.annual"
            }
        },
        "gender": "female",
        "uid": "5aF6UQIH4zR0txD1HaumxdIzUsB2",
        "id": "5aF6UQIH4zR0txD1HaumxdIzUsB2",
        "subscribe": null,
        "get": 1896,
        "email": "teste30@gmail.com",
        "level": 2,
        "name": "Paloma Teste",
        "registerDate": new Date("2024-03-05"),
        "restrictions": ["celiac", "ovovegetarian"],
        "objective": 2,
        "role": null,
        "height": null,
        "mealsADay": null,
        "weight": 65,
        "desiredWeight": null,
        "desiredWeightLossByWeek": 0.5,
        "tmb": 2104
    },
    {
        "activityLevel": 0,
        "age": 45,
        "coins": 103,
        "desiredWeight": null,
        "desiredWeightLossByWeek": 0.5,
        "gender": "male",
        "id": "46lgUMWDTwNfv0hQP8T7hRfGiIg2",
        "get": 2732.448,
        "email": "bshshs@jsks.com",
        "level": 5,
        "name": "jsjs hshsh",
        "registerDate": new Date("2024-01-01"),
        "objective": 0,
        "preferences": null,
        "restrictions": ['allergic'],
        "role": "user",
        "signature": {
            "gym": {
                "title": "Studio Treino",
                "id": "QAzN8az7ajx3xJgNG49b",
                "coupon": "#studiotreino",
                "registerDate": new Date('2024-05-30'),
            },
            "plan": {
                "isClicked": false,
                "type": "Anual",
                "androidID": null,
                "value": 350,
                "order": null,
                "currency": null,
                "id": null,
                "description": "Nessa modalidade <b>uma vez ao ano</b> você paga:",
                "title": "Anual",
                "isTrial": false,
                "valid": true,
                "iosID": null
            }
        },
        "subscribe": null,
        "height": 180,
        "mealsADay": null,
        "weight": 110,
        "tmb": 2329,
        "uid": "46lgUMWDTwNfv0hQP8T7hRfGiIg2",
    }];